name: WPCS check

on: pull_request

jobs:
  phpcs:
      name: WPCS
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v2
        - name: Setup PHP with tools
          uses: shivammathur/setup-php@v2
          with:
            php-version: '8.0'
            tools: none
        - name: WPCS check
          uses: 10up/wpcs-action@stable
          with:
            use_local_config: 'true'
